# -*- coding: utf-8 -*-
"""Image Captioning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Wy5efABspyYY1_pOWq9HQDEoYZbw8RHg
"""

from google.colab import drive
drive.mount('/content/drive')

# New Yorker Caption Contest - Image Captioning with ViT-GPT2
# Full Google Colab Notebook: Training + ONNX Export + TensorRT Inference

# =============================
# STEP 1: Install dependencies
# =============================
!pip install -q datasets transformers torchvision accelerate
!pip install -q onnx onnxruntime
!pip install -q tensorrt --extra-index-url https://pypi.ngc.nvidia.com
!pip install -q pycuda

# =============================
# STEP 2: Load and Explore Dataset
# =============================
from datasets import load_dataset
import matplotlib.pyplot as plt

dataset = load_dataset('jmhessel/newyorker_caption_contest',
                       name='ranking_from_pixels', split="train")

# Preview a cartoon
sample = dataset[0]
print(sample)
plt.imshow(sample['image'])
plt.axis('off')
plt.title("Sample Cartoon")
plt.show()
print("Captions:", sample['caption_choices'])

# =============================
# STEP 3: Preprocessing
# =============================
from transformers import VisionEncoderDecoderModel, ViTImageProcessor, AutoTokenizer
from torchvision.transforms import Compose, Resize, ToTensor, Normalize
import torch
from datasets import Features, Value, Sequence, Array3D
import numpy as np

model_name = "nlpconnect/vit-gpt2-image-captioning"
processor = ViTImageProcessor.from_pretrained(model_name)
tokenizer = AutoTokenizer.from_pretrained(model_name)

model = VisionEncoderDecoderModel.from_pretrained(model_name)

transform = Compose([
    Resize((224, 224)),
    ToTensor(),
    Normalize([0.5], [0.5])
])

# Define expected data types for features
# Use Array3D to represent pixel_values as a 3D array
features = Features({
    'pixel_values': Array3D(dtype="float32", shape=(3, 224, 224)),  # 3D array for pixel_values
    'labels': Sequence(Value('int64')),  # Sequence for labels (token IDs)
})

def preprocess(example):
    image = example['image'].convert("RGB")
    caption = example['caption_choices'][0]

    # Ensure image tensor is shape (3, 224, 224) and convert to tensor
    pixel_values = processor(images=image, return_tensors="pt").pixel_values
    # Convert to a regular PyTorch tensor (not a Hugging Face Tensor)
    pixel_values = pixel_values.squeeze(0).type(torch.FloatTensor)
    # Convert to NumPy array
    pixel_values = pixel_values.numpy() # Convert to NumPy array

    # Tokenize caption and convert to tensor
    labels = tokenizer(caption, padding="max_length", truncation=True, max_length=128, return_tensors="pt").input_ids.squeeze(0)
    # Convert to a regular PyTorch tensor (not a Hugging Face Tensor)
    labels = labels.type(torch.LongTensor)
     # Convert to a list of integers (for 'labels' feature)
    labels = labels.tolist() # Convert to a list


    return {
        "pixel_values": pixel_values,
        "labels": labels
    }

# Apply preprocessing with type specification
processed_dataset = dataset.map(preprocess,
                                remove_columns=dataset.column_names,
                                features=features)

# =============================
# STEP 4: Training
# =============================
from torch.utils.data import DataLoader

def collate_fn(batch):
    # Stack pixel_values as before
    pixel_values = torch.stack([torch.tensor(item['pixel_values']) for item in batch])

    # Convert labels to tensors before stacking
    labels = [torch.tensor(item['labels']) for item in batch]  # Convert each item to tensor
    labels = torch.stack(labels)  # Stack the tensors

    return {"pixel_values": pixel_values, "labels": labels}

train_loader = DataLoader(processed_dataset, batch_size=8, shuffle=True, collate_fn=collate_fn)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Device using: ", device)
model.to(device)
model.train()

optimizer = torch.optim.AdamW(model.parameters(), lr=5e-5)
from tqdm import tqdm

train_losses = []
for epoch in range(3):
    epoch_loss = 0
    loop = tqdm(train_loader, leave=True)
    for batch in loop:
        pixel_values = batch["pixel_values"].to(device)
        labels = batch["labels"].to(device)

        outputs = model(pixel_values=pixel_values, labels=labels)
        loss = outputs.loss
        loss.backward()
        optimizer.step()
        optimizer.zero_grad()

        epoch_loss += loss.item()
        loop.set_description(f"Epoch {epoch}")
        loop.set_postfix(loss=loss.item())

    # Average loss for the epoch
    avg_loss = epoch_loss / len(train_loader)
    train_losses.append(avg_loss)
    print(f"Epoch {epoch} - Average Loss: {avg_loss:.4f}")

# ======================================
# STEP 5: Visualise the training loss
# ======================================
import matplotlib.pyplot as plt

plt.plot(range(1, len(train_losses)+1), train_losses, marker='o')
plt.title("Training Loss per Epoch")
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.grid(True)
plt.show()

# =============================
# STEP 6: Save ONNX Encoder
# =============================
model.eval()
encoder = model.get_encoder()

dummy_image = torch.randn(1, 3, 224, 224).to(device)
torch.onnx.export(
    encoder,
    dummy_image,
    "image_captioning_vit_encoder.onnx",
    input_names=["pixel_values"],
    output_names=["encoder_hidden_states"],
    opset_version=14
)
print("ONNX model saved as image_captioning_vit_encoder.onnx")

# =============================
# STEP 7: Convert to TensorRT
# =============================
import tensorrt as trt
TRT_LOGGER = trt.Logger()

builder = trt.Builder(TRT_LOGGER)
network = builder.create_network(1 << int(trt.NetworkDefinitionCreationFlag.EXPLICIT_BATCH))
parser = trt.OnnxParser(network, TRT_LOGGER)

with open("image_captioning_vit_encoder.onnx", "rb") as f:
    if not parser.parse(f.read()):
        for i in range(parser.num_errors):
            print(parser.get_error(i))

# Create a config object
config = builder.create_builder_config()
# Set max_workspace_size through the config object using set_memory_pool_limit
config.set_memory_pool_limit(trt.MemoryPoolType.WORKSPACE, 1 << 30)
config.set_flag(trt.BuilderFlag.FP16) # Use config.set_flag to enable FP16
# Build the engine using the config
# In newer TensorRT versions, use build_serialized_network instead
serialized_engine = builder.build_serialized_network(network, config)  # Get serialized engine



with open("image_captioning_vit_encoder.trt", "wb") as f:
    f.write(serialized_engine)
print("TensorRT engine saved as image_captioning_vit_encoder.trt")

